name: Email Step Test

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3000325@ds.study.iitm.ac.in
        run: echo "Hello, world!"
